import type { Metadata } from "next";
import Link from "next/link";
import QuoteRequestForm from "../../components/QuoteRequestForm";
import { getPublicProductBySlug } from "../../lib/catalogue/catalogue-repository";
import { normalizePublicDiscoveryContext, normalizePublicListingSlug } from "../../lib/catalogue/quote-handoff";
import type { PublicCatalogueProduct } from "../../lib/catalogue/types";
import { productCategory, productSummary } from "../../components/PublicStitch";

type QuotePageProps = { searchParams?: Promise<Record<string, string | string[] | undefined>> | Record<string, string | string[] | undefined> };
export const metadata: Metadata = { title: "Quote request | SpaceKonceptRental", description: "Submit an event furniture rental enquiry with event date, venue, requested listings, quantities, and setup notes for manual team follow-up.", openGraph: { title: "Quote request | SpaceKonceptRental", description: "Submit a rental enquiry for manual follow-up from the SpaceKonceptRental team.", siteName: "SpaceKonceptRental", type: "website", url: "/quote" } };
function firstSearchParam(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
async function resolveQuoteListingContext(searchParams: QuotePageProps["searchParams"]) { if (!searchParams) return { product:null, requestedSlug:undefined, category:undefined, event:undefined, search:undefined }; const resolved = await searchParams; const slug = normalizePublicListingSlug(firstSearchParam(resolved.listing)); return { product: slug ? await getPublicProductBySlug(slug) : null, requestedSlug: slug, category: normalizePublicListingSlug(firstSearchParam(resolved.category)), event: normalizePublicListingSlug(firstSearchParam(resolved.event)), search: normalizePublicDiscoveryContext(firstSearchParam(resolved.search)) }; }
function buildInitialItemsText({ category, event, product, requestedSlug, search }: { category?: string; event?: string; product: PublicCatalogueProduct | null; requestedSlug?: string; search?: string }) { return [product?.name ?? (requestedSlug ? `Listing reference: ${requestedSlug}` : undefined), category ? `Category interest: ${category}` : undefined, event ? `Event detail: ${event}` : undefined, search ? `Search interest: ${search}` : undefined].filter(Boolean).join("\n"); }
function SelectionPanel({ product, requestedSlug, category, event, search }: { product: PublicCatalogueProduct | null; requestedSlug?: string; category?: string; event?: string; search?: string }) { return <div className="stitch-panel"><p className="stitch-eyebrow">Your Selection</p><h2>{product ? product.name : requestedSlug ? "Selected listing unavailable" : "General rental enquiry"}</h2>{product ? <><p>{productSummary(product)}</p><dl className="stitch-facts"><div><dt>Selected Rental Items</dt><dd>{product.name}</dd></div><div><dt>Category</dt><dd>{productCategory(product)}</dd></div></dl><Link className="stitch-link-button stitch-link-button--quiet" href={`/catalogue/${product.slug}`}>View Details</Link></> : <><p>Share the requested listings or items you have in mind. The listing link may be old or unavailable. Your selected rental items and selected setups can be added from the catalogue or setup pages. You can also type requested pieces directly into the form and share more details.</p>{(requestedSlug || category || event || search) ? <dl className="stitch-facts">{requestedSlug ? <><p>Listing reference: {requestedSlug} starts this rental request.</p><div><dt>Selected listing reference</dt><dd>{requestedSlug}</dd></div></> : null}{category ? <div><dt>Category</dt><dd>{category}</dd></div> : null}{event ? <div><dt>Event details</dt><dd>{event}</dd></div> : null}{search ? <div><dt>Search</dt><dd>{search}</dd></div> : null}</dl> : null}</>}</div>; }
export default async function QuotePage({ searchParams }: QuotePageProps = {}) { const context = await resolveQuoteListingContext(searchParams); const initialItemsText = buildInitialItemsText({ category: context.category, event: context.event, product: context.product, requestedSlug: context.requestedSlug, search: context.search }); return <><section className="stitch-section"><div className="stitch-container"><div className="stitch-section-heading"><p className="stitch-eyebrow">Request Quote</p><h1>Request a rental quote</h1><p>Share contact details, event date, venue, requested listings, quantities, and setup notes for event furniture rental planning. This is enquiry intake only and does not confirm final rental details.</p></div><div className="stitch-quote-grid"><div className="stitch-panel"><SelectionPanel product={context.product} requestedSlug={context.requestedSlug} category={context.category} event={context.event} search={context.search} /><div className="stitch-panel" style={{ marginTop: 20 }}><p className="stitch-eyebrow">What happens next</p><h2>What happens after you enquire</h2><p>Submission starts an enquiry and does not set aside furniture.</p><p>Team reviews fit before follow-up.</p><p>The form is enquiry intake only and does not set aside furniture or finish rental details.</p><h2>Manual team follow-up</h2><p>We received your rental enquiry when the form succeeds. Our team will review your selection and follow up with a tailored proposal.</p><p>This request does not confirm final rental details.</p></div></div><div className="stitch-panel"><p className="stitch-eyebrow">Quote request form</p><nav aria-label="Quote request recovery" className="stitch-actions"><Link className="stitch-button stitch-button--secondary" href="/listings">Browse listings</Link><Link className="stitch-button stitch-button--secondary" href="/events">Plan event setups</Link></nav><h2>Check your enquiry details</h2><p>Before you send, confirm your contact details, event date, venue or location, requested listings or items, quantities, alternates, setup, access, and timing notes.</p><QuoteRequestForm initialItemsText={initialItemsText} initialListingSlug={context.requestedSlug} /></div></div></div></section></>; }
