import type { Metadata } from "next";
import Link from "next/link";
import QuoteRequestForm from "../../components/QuoteRequestForm";
import { getPublicProductBySlug } from "../../lib/catalogue/catalogue-repository";
import { normalizePublicDiscoveryContext, normalizePublicListingSlug } from "../../lib/catalogue/quote-handoff";
import type { PublicCatalogueProduct } from "../../lib/catalogue/types";
import { productCategory, productSummary } from "../../components/PublicStitch";

type QuotePageProps = { searchParams?: Promise<Record<string, string | string[] | undefined>> | Record<string, string | string[] | undefined> };
export const metadata: Metadata = { title: "Request Quote | SpaceKonceptRental", description: "Submit a rental enquiry for manual team follow-up." };
function firstSearchParam(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
async function resolveQuoteListingContext(searchParams: QuotePageProps["searchParams"]) { if (!searchParams) return { product:null, requestedSlug:undefined, category:undefined, event:undefined, search:undefined }; const resolved = await searchParams; const slug = normalizePublicListingSlug(firstSearchParam(resolved.listing)); return { product: slug ? await getPublicProductBySlug(slug) : null, requestedSlug: slug, category: normalizePublicListingSlug(firstSearchParam(resolved.category)), event: normalizePublicListingSlug(firstSearchParam(resolved.event)), search: normalizePublicDiscoveryContext(firstSearchParam(resolved.search)) }; }
function buildInitialItemsText({ category, event, product, requestedSlug, search }: { category?: string; event?: string; product: PublicCatalogueProduct | null; requestedSlug?: string; search?: string }) { return [product?.name ?? (requestedSlug ? `Listing reference: ${requestedSlug}` : undefined), category ? `Category interest: ${category}` : undefined, event ? `Event detail: ${event}` : undefined, search ? `Search interest: ${search}` : undefined].filter(Boolean).join("\n"); }
function SelectionPanel({ product, requestedSlug, category, event, search }: { product: PublicCatalogueProduct | null; requestedSlug?: string; category?: string; event?: string; search?: string }) { return <div className="stitch-panel"><p className="stitch-eyebrow">Your Selection</p><h2>{product ? product.name : "Quote List"}</h2>{product ? <><p>{productSummary(product)}</p><dl className="stitch-facts"><div><dt>Selected Rental Items</dt><dd>{product.name}</dd></div><div><dt>Category</dt><dd>{productCategory(product)}</dd></div></dl><Link className="stitch-link-button stitch-link-button--quiet" href={`/catalogue/${product.slug}`}>View Details</Link></> : <><p>Your selected rental items and selected setups can be added from the catalogue or setup pages. You can also type requested pieces directly into the form.</p>{(requestedSlug || category || event || search) ? <dl className="stitch-facts">{requestedSlug ? <div><dt>Reference</dt><dd>{requestedSlug}</dd></div> : null}{category ? <div><dt>Category</dt><dd>{category}</dd></div> : null}{event ? <div><dt>Event details</dt><dd>{event}</dd></div> : null}{search ? <div><dt>Search</dt><dd>{search}</dd></div> : null}</dl> : null}</>}</div>; }
export default async function QuotePage({ searchParams }: QuotePageProps = {}) { const context = await resolveQuoteListingContext(searchParams); const initialItemsText = buildInitialItemsText({ category: context.category, event: context.event, product: context.product, requestedSlug: context.requestedSlug, search: context.search }); return <><section className="stitch-section"><div className="stitch-container"><div className="stitch-section-heading"><p className="stitch-eyebrow">Request Quote</p><h1>Tell us what you need for your rental enquiry.</h1><p>Share your selection, event details, and contact preference. This is enquiry intake only and does not confirm final rental details.</p></div><div className="stitch-quote-grid"><div className="stitch-panel"><SelectionPanel product={context.product} requestedSlug={context.requestedSlug} category={context.category} event={context.event} search={context.search} /><div className="stitch-panel" style={{ marginTop: 20 }}><p className="stitch-eyebrow">What happens next</p><h2>Manual team follow-up</h2><p>We received your rental enquiry when the form succeeds. Our team will review your selection and follow up with a tailored proposal.</p><p>This request does not confirm final rental details.</p></div></div><div className="stitch-panel"><p className="stitch-eyebrow">Quote request form</p><QuoteRequestForm initialItemsText={initialItemsText} initialListingSlug={context.requestedSlug} /></div></div></div></section></>; }
