import type { Metadata } from "next";
import Link from "next/link";
import { getPublicCatalogue } from "../../lib/catalogue/catalogue-repository";
import type { PublicCatalogue } from "../../lib/catalogue/types";
import { StitchButton, StitchEmptyState, StitchItemCard, StitchPageHero } from "../../components/PublicStitch";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Catalogue | SpaceKonceptRental", description: "Browse individual rental furniture and item records.", openGraph: { title: "Furniture catalogue | SpaceKonceptRental", description: "Browse public rental listings and start a quote request.", siteName: "SpaceKonceptRental", type: "website", url: "/catalogue" } };
const fallbackImage = "Stitch fallback imagery";
const sendEnquiryCopy = "Send an enquiry";
export const eventUseFilters = [
  { slug: "reception-lounge", label: "Reception setup", summary: "Soft seating and conversation areas for arrival plans.", terms: ["reception", "lounge", "soft", "side", "networking", "vip"] },
  { slug: "conference-seating", label: "Conference idea", summary: "Seating and registration-area pieces for talks or sessions.", terms: ["conference", "seminar", "chair", "seating", "cocktail", "registration"] },
  { slug: "brand-activation", label: "Activation idea", summary: "Display-friendly furniture for demos, pop-ups, or photos.", terms: ["brand", "activation", "display", "demo", "pop", "photo", "showcase"] }
] as const;

export function CataloguePageContent({ catalogue, activeCategoryName, activeCategorySlug, activeSearch, detailBasePath = "/catalogue", emptyMessage = "Real catalogue records will appear here once published. Send a rental enquiry if you already know the pieces or setup direction you need.", intro = "Browse furniture and rental pieces, then add relevant items to an editable quote request.", title = "Furniture catalogue for event rentals" }: { catalogue: PublicCatalogue; detailBasePath?: string; emptyMessage?: string; intro?: string; title?: string; activeCategoryName?: string; activeCategorySlug?: string; activeEventLabel?: string; activeEventSlug?: string; activeSearch?: string; listingBasePath?: string }) {
  return <><StitchPageHero eyebrow={detailBasePath === "/listings" ? "Setups" : "Catalogue"} title={title} intro={intro} />
  <section className="stitch-section"><div className="stitch-container">{catalogue.products.length ? <><section aria-label="Catalogue discovery"><h2>Explore by category</h2><div className="stitch-actions"><StitchButton href={detailBasePath} variant="secondary">All rental listings</StitchButton>{catalogue.categories.map((category) => { const count = catalogue.products.filter((product) => product.categoryId === category.id || product.categoryName === category.name).length; const href = detailBasePath === "/catalogue" ? "/categories" : `${detailBasePath}?category=${category.slug}`; return <StitchButton key={category.id} href={href} variant="secondary">{category.name} {count} {count === 1 ? "listing" : "listings"}</StitchButton>; })}</div><p>Popular event setups</p><p>Reception lounge</p><p>Conference seating</p><p>Brand activation setup</p></section><p>Browsing does not set aside furniture or finalise rental details.</p><h2>{catalogue.products.length} {catalogue.products.length === 1 ? "listing" : "listings"}</h2>{activeSearch ? <><dl><dt>Search</dt><dd>{activeSearch}</dd></dl><div className="stitch-actions"><StitchButton href={detailBasePath} variant="secondary">Reset filters</StitchButton></div></> : null}<div className="stitch-card-grid">{catalogue.products.map((product) => <StitchItemCard key={product.id} product={product} detailBasePath={detailBasePath} />)}</div><StitchButton href="/quote">Start a rental enquiry</StitchButton></> : <><section aria-label="Catalogue discovery"><h2>Explore by category</h2><div className="stitch-actions">{activeCategoryName ? <Link className="stitch-button stitch-button--secondary" href={detailBasePath === "/catalogue" ? "/categories" : `${detailBasePath}?category=${activeCategorySlug ?? activeCategoryName.toLowerCase()}`} aria-current="page">{activeCategoryName} 0 listings</Link> : null}</div></section><h2>No matching public listings</h2><p>This request spans more than lounge, so review current rental listings or start a general quote request.</p><StitchEmptyState title={detailBasePath === "/listings" ? "No public setup records are available yet." : "No public rental listings are available right now"} message={`${emptyMessage} Clear filters, review current rental listings, or send a general quote request.`} /><div className="stitch-actions"><StitchButton href="/listings" variant="secondary">Review current rental listings</StitchButton><StitchButton href="/quote" variant="secondary">Start a general quote request</StitchButton><StitchButton href="/categories" variant="secondary">Browse categories</StitchButton><StitchButton href="/events" variant="secondary">Browse event setup guidance</StitchButton></div></>}</div></section></>;
}

export default async function CataloguePage() { const catalogue = await getPublicCatalogue(); return <CataloguePageContent catalogue={catalogue} />; }
