import type { Metadata } from "next";
import Image from "next/image";
import { StitchButton, StitchPageIntro, stitchImages } from "../../components/PublicStitch";

export const metadata: Metadata = { title: "Event setups | SpaceKonceptRental", description: "Supporting event furniture setup guidance for quote request planning." };

export default function EventsPage() {
  return <><section className="stitch-editorial-hero"><div className="stitch-container stitch-editorial-hero__grid"><StitchPageIntro eyebrow="Events" title="Plan an event setup." intro="Use event context to describe the rental mood, guest flow, and setup direction you want the team to review." actions={<><StitchButton href="/listings">Browse Setups</StitchButton><StitchButton href="/quote" variant="secondary">Start a rental enquiry</StitchButton></>} /><div className="stitch-editorial-hero__image"><Image src={stitchImages.corporateImage} alt="Corporate reception event furniture setup" /></div></div></section><section className="stitch-section"><div className="stitch-container stitch-feature-grid"><article className="stitch-feature"><h3>Match the setup type</h3><p>Use reception, lounge, dining, or showcase context to explain the event setting.</p></article><article className="stitch-feature"><h3>Capture practical notes</h3><p>Share quantities, placement notes, timing, access, and alternates in the enquiry.</p></article><article className="stitch-feature"><h3>Manual review</h3><p>The team reviews submitted details before preparing a tailored proposal.</p></article></div></section><section className="stitch-section stitch-section--tonal"><div className="stitch-container stitch-event-image-grid"><Image src={stitchImages.galaImage} alt="Gala lounge furniture setup" /><Image src={stitchImages.exhibitionImage} alt="Exhibition event furniture setup" /></div></section></>;
}
